### ISSUE TITLE
Refactor the `sysml2xml.py` in order to use classes – Stint 1

### ISSUE THREAD

**Issue by martinaxgloria** [icub-tech-iit/study-alexandria#11]
## Task Description

We would like the python script to mirror the SysML architecture. For example, for each component, there will be a function `from_sysml` and a `to_xml`. 

This is propedeutic for future developments.

## Definition of Done

The code has been refactored in order to:

- [x] Add the python classes reflecting the sysml structure without using them in the code
- ~[x] Cleanup the sysml parsing, using `sysml2py` instead of the hand-crafted parsing~ -> https://github.com/Westfall-io/sysml2py/issues/84
- [x] Reorganize the sysml files structure in order to go in this direction -> https://github.com/icub-tech-iit/study-alexandria/issues/2#issuecomment-2437950851. Morever this will allow to solve also this issue (#12)
- [x] Write fromSysML for the single classes with in mind the new sysml files architecture
